steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}", "./"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}",
        "--region",
        "us-east4",
        "--platform",
        "managed",
        "--service-account",
        "${_SERVICE_ACCOUNT}"
      ]